import { chmod, mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { releaseVersion } from "./release-version.ts";

export const pluginNames = [
	"claude-mod",
	"claude-hooks",
	"codex-hooks",
] as const;

/** Keep Git installs and release archives self-contained, without symlinks. */
export async function syncPluginAssets(root = resolve(import.meta.dir, "..")) {
	const skill = await Bun.file(join(root, "skills/routing/SKILL.md")).text();
	for (const name of pluginNames) {
		const dir = join(root, "packages", name);
		const manifest =
			name === "codex-hooks" ? ".codex-plugin" : ".claude-plugin";
		const { version } = await Bun.file(
			join(dir, manifest, "plugin.json"),
		).json();
		releaseVersion(`v${version}`);
		await mkdir(join(dir, "bin"), { recursive: true });
		await mkdir(join(dir, "skills/routing"), { recursive: true });
		await Bun.write(join(dir, "skills/routing/SKILL.md"), skill);
		const launcher = join(dir, "bin/spatz");
		await Bun.write(
			launcher,
			`#!/bin/sh
# Generated by scripts/plugin-assets.ts; version follows the plugin manifest.
# Hooks discard stderr. The outer launcher records one fixed marker per failed hook launch.
owner=$SPATZ_LAUNCHER_ACTIVE
export SPATZ_LAUNCHER_ACTIVE=1
cmd=$1
failed() {
    if [ "$cmd" = hook ] && [ -z "$owner" ] && [ -n "$HOME" ]; then
        (umask 077; mkdir -p "$HOME/.spatz" && printf '1\\n' >>"$HOME/.spatz/launcher-failures") 2>/dev/null || :
    fi
}
run() {
    [ "$cmd" = hook ] || exec "$@"
    "$@"
    status=$?
    [ "$status" -eq 0 ] || failed
    exit "$status"
}
if [ -z "$SPATZ_LAUNCHER" ] && command -v spatz >/dev/null 2>&1; then
    export SPATZ_LAUNCHER=1
    run spatz "$@"
elif command -v bunx >/dev/null 2>&1; then
    run bunx @spatz/cli@${version} "$@"
elif command -v npx >/dev/null 2>&1; then
    run npx -y @spatz/cli@${version} "$@"
fi
echo "install the spatz CLI: npm i -g @spatz/cli" >&2
failed
exit 1
`,
		);
		await chmod(launcher, 0o755);
	}
}

if (import.meta.main) await syncPluginAssets();
