import { chmod, mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { releaseVersion } from "./release-version.ts";

export const pluginNames = [
	"claude-mod",
	"claude-hooks",
	"codex-hooks",
] as const;

/** Keep Git installs and release archives self-contained, without symlinks. */
export async function syncPluginAssets(root = resolve(import.meta.dir, "..")) {
	const skill = await Bun.file(join(root, "skills/routing/SKILL.md")).text();
	for (const name of pluginNames) {
		const dir = join(root, "packages", name);
		const manifest =
			name === "codex-hooks" ? ".codex-plugin" : ".claude-plugin";
		const { version } = await Bun.file(
			join(dir, manifest, "plugin.json"),
		).json();
		releaseVersion(`v${version}`);
		await mkdir(join(dir, "bin"), { recursive: true });
		await mkdir(join(dir, "skills/routing"), { recursive: true });
		await Bun.write(join(dir, "skills/routing/SKILL.md"), skill);
		const launcher = join(dir, "bin/spatz");
		await Bun.write(
			launcher,
			`#!/bin/sh
# Generated by scripts/plugin-assets.ts; version follows the plugin manifest.
# spatz hook always exits 0, so a failed hook call failed here. Hooks hide stderr:
# one line per failure in ~/.spatz/launcher-failures shows it in spatz stats.
failed() {
    [ "$1" = hook ] && mkdir -p "$HOME/.spatz" 2>/dev/null &&
        printf '%s\\n' "$2" >>"$HOME/.spatz/launcher-failures" 2>/dev/null
}
run() {
    [ "$cmd" = hook ] || exec "$@"
    "$@" && exit 0
    status=$?
    failed hook "$event"
    exit "$status"
}
cmd=$1 event=$2
if [ -z "$SPATZ_LAUNCHER" ] && command -v spatz >/dev/null 2>&1; then
    export SPATZ_LAUNCHER=1
    run spatz "$@"
elif command -v bunx >/dev/null 2>&1; then
    run bunx @spatz/cli@${version} "$@"
elif command -v npx >/dev/null 2>&1; then
    run npx -y @spatz/cli@${version} "$@"
fi
echo "install the spatz CLI: npm i -g @spatz/cli" >&2
failed "$cmd" "$event"
exit 1
`,
		);
		await chmod(launcher, 0o755);
	}
}

if (import.meta.main) await syncPluginAssets();
